volumes:
  pg_data_production:
  static_volume:

services:
  
  db:
    image: postgres:13.10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  
  backend:
    image: korny98/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  
  frontend:
    image: korny98/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    image: korny98/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
